### ISSUE TITLE
Publish PGP key to allow signature verification of Bultitude artefacts

### ISSUE THREAD

**Issue by glts** [TimoFreiberg/bultitude#8]
I’m revisiting an old Leiningen ticket about dependency auditing technomancy/leiningen#1608, and noticed that you haven’t published your PGP public key to public key servers (`gpg --send-keys E530F3B60F8C007EA9C76951C1877D95FC999246`). That makes it impossible to verify the signature of Bultitude 0.3.0.

(I know that this ticket is a bit of a nuisance, so feel free to close if you can’t be bothered.)

**Comment by TimoFreiberg** [comment]
Thanks for checking up on this.
I published it now, do you want to check again?

**Comment by glts** [comment]
That was prompt, thank you! Unfortunately, I still cannot verify the Bultitude 0.3.0 artefact.

```
$ gpg --verify bultitude-0.3.0.jar.asc
gpg: assuming signed data in 'bultitude-0.3.0.jar'
gpg: Signature made Mon 15 Oct 2018 13:41:27 CEST
gpg:                using RSA key E530F3B60F8C007EA9C76951C1877D95FC999246
gpg: Can't check signature: No public key
```

The public key isn’t in the pool … It’s curious, this is the only dependency in Leiningen where I can’t find a key.

**Comment by TimoFreiberg** [comment]
Oh man, yeah that was my first time using gpg... I had different private keys on each machine :/
I was wondering where the ID `E530F3B60F8C007EA9C76951C1877D95FC999246` came from, now I've found it.
It should be published now!

**Comment by glts** [comment]
I think the `~/.gnupg` directory is sort of a ‘life-long’ thing … it’s where all your secrets live, so you just carry it along from machine to machine, and protect it well. That’s the idea. At least that’s what I do! Of course, if the passphrase is gone you won’t be able to use that key to sign in the future, but the signatures that have been made are still valid.

Anyway, I can verify the signature now, so thanks much! And don’t mind me, I just landed here looking at a couple of old Leiningen tickets, hoping to close a few of them … cheers
